### ISSUE TITLE
Wrong import path?

### ISSUE THREAD

**Issue by emas80** [mongodb/go-client-mongodb-atlas#119]
When I add the import to my go file (XXX/YYYY/ZZZZ file)
```
import "go.mongodb.org/atlas/mongodbatlas"
```

all I get is this message:

```
go: finding module for package go.mongodb.org/atlas/mongodbatlas
go: found go.mongodb.org/atlas/mongodbatlas in go.mongodb.org/atlas v0.3.0
go: github.com/XXX/YYYY/ZZZZ imports
	go.mongodb.org/atlas/mongodbatlas: go.mongodb.org/atlas@v0.3.0: parsing go.mod:
	module declares its path as: github.com/mongodb/go-client-mongodb-atlas
	        but was required as: go.mongodb.org/atlas
```

am I doing anything wrong?

**Comment by gssbzn** [comment]
Hi @emas80, sorry about this, I think this is due to us not having tagged a version since we introduced the vanity url
Right now you can get around this issue by installing from master

```bash
go get -u go.mongodb.org/atlas@master
```

We'll try to make a tag as soon as possible

**Comment by themantissa** [comment]
@emas80 newest version is out, 0.4.0, should be what was needed.

**Comment by themantissa** [comment]
@emas80 will assume things are okay for you and close the issue.  However feel free to reach out if this did not help.
