### ISSUE TITLE
Provide Alert Configurations API

### ISSUE THREAD

**Issue by Knappek** [mongodb/go-client-mongodb-atlas#18]
https://docs.atlas.mongodb.com/reference/api/alert-configurations/

**Comment by PacoDw** [comment]
Hello, @Knappek thanks for your review, in the future we will add more entry point from the API for the community.

**Comment by themantissa** [comment]
Just to add @Knappek we should have a mechanism soon to get this feedback in more directly and rank resources needed going forward but until then issues are a great way to request resources not yet supported.     I'll be sure to update READMEs once we have that mechanism in place.

**Comment by themantissa** [comment]
@Knappek we now have UserVoice for feature requests.  Go here: https://feedback.mongodb.com/forums/924145-atlas and simply file the request under the Terraform category and other users can also comment and vote.  I'll be adding this link to the READMEs as well but wanted to let you know and close this issue out once you have a chance to submit the request.
