### ISSUE TITLE
undefined: io.Discard and io.ReadAll in latest code push

### ISSUE THREAD

**Issue by DrewCurd** [mongodb/go-client-mongodb-atlas#267]
**Describe the bug**
Currently, the Go Client is broken due to io.Discard and io.ReadAll being undefined in latest version of the code.

**Expected behavior**
Should be able to run the Go Client without getting undefined errors unrelated to my code.

**Logs**
```
# go.mongodb.org/atlas/mongodbatlas
/root/go/src/go.mongodb.org/atlas/mongodbatlas/mongodbatlas.go:450:20: undefined: io.Discard
/root/go/src/go.mongodb.org/atlas/mongodbatlas/mongodbatlas.go:521:15: undefined: io.ReadAll
Error: Process completed with exit code 2.
```

**Comment by gssbzn** [comment]
Hi @DrewCurd, I'm assuming this is a go version prior to 1.16 where `io.Discard` and `io.ReadAll` where added and `ioutil` deprecated, sadly we dropped support for any version prior to 1.16 (https://github.com/mongodb/go-client-mongodb-atlas/pull/242) in line with our support policy, from our [README](https://github.com/mongodb/go-client-mongodb-atlas/blob/master/README.md)
> Note that go-client-mongodb-atlas only supports the two most recent major versions of Go.

Which is also aligned with the [go support policy ](https://golang.org/doc/devel/release#policy)





https://golang.org/doc/devel/release#policy
