### ISSUE TITLE
"CloudProviderSnapshots.GetOneCloudProviderSnapshot()" method returns already deleted snapshot

### ISSUE THREAD

**Issue by rdharmedran** [mongodb/go-client-mongodb-atlas#315]
**Describe the bug**
I created a snapshot and deleted it using Atlas UI.
But "CloudProviderSnapshots.GetOneCloudProviderSnapshot()" method   in atlas client returns already deleted snapshot

	snapshot, res, err := client.CloudProviderSnapshots.GetOneCloudProviderSnapshot(context.TODO(), snapshotRequest)
	if err != nil {
		log.Infof("Read - errorss reading project with id(%s): %s", snapshotId, err)
		return handler.ProgressEvent{
			OperationStatus:  handler.Failed,
			Message:          "Resource Not Found",
			HandlerErrorCode: cloudformation.HandlerErrorCodeNotFound}, nil
	}

**Expected behavior**
 it should return error( "Resource Not Found")

**Logs**
If applicable, add logs to help explain your problem.

**Desktop (please complete the following information):**
 - Windows
 -go.mongodb.org/atlas v0.17.0

**Additional context**

**Comment by gssbzn** [comment]
Hi @rdharmedran thanks for reporting this sadly this would be a problem with the API and not the SDK itself, I have created an internal report to the team responsible of the feature but I'll also advise you to create a suport case for Atlas reporting the same 

Given there's not much we can do in the SDK side of things I'll be closing this ticket
