### ISSUE TITLE
CloudQuery Source Plugin?

### ISSUE THREAD

**Issue by yevgenypats** [mongodb/go-client-mongodb-atlas#375]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a MongoDB Atlas plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync MongoDB Atlas APIs to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview) (We already support [MongoDB](https://www.cloudquery.io/docs/plugins/destinations/mongodb/overview) destination, which is quite popular destination for ELT workloads and hence the request for the Atlas connector).

Best,
Yevgeny

**Comment by Zuhairahmed** [comment]
hi @yevgenypats great to meet you! Happy to learn more and explore ways we can collaborate together on this for our joint-customers. Feel free to drop me an email and we can better coordinate (zuhair.ahmed@mongodb.com). Can find time to sync this Friday on zoom or later next week if that works on your end as well.

**Comment by wtrocki** [comment]
@yevgenypats Thank you for reaching out. As this is a nonsoftware related request I'm closing the issue.
