### ISSUE TITLE
`setListOptions` does not include options from embedded `ListOptions`

### ISSUE THREAD

**Issue by Freyert** [mongodb/go-client-mongodb-atlas#381]
**Describe the bug**
[`setListOptions`](https://github.com/mongodb/go-client-mongodb-atlas/blob/0a896b507bc8b88891eb64902c91c2224153e31f/mongodbatlas/mongodbatlas.go#L533) only captures struct fields from 1 level deep. It will not capture options from embedded structs like `ListOptions`.

So when I do the following:

```go
mongodbatlas.EventListOptions{
		ListOptions: mongodbatlas.ListOptions{
			IncludeCount: false,
		},
		EventType: []string{
			"API_KEY_CREATED",
		},
	}
```

`setListOptions` drops:

```go
ListOptions: mongodbatlas.ListOptions{
  IncludeCount: false,
},
```

**Expected behavior**

When I use a struct that embeds `ListOptions`, the parameters from the embedded `ListOptions` will be added to my request.

**Logs**
If applicable, add logs to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Lib Version [e.g. 0.6.0]

**Additional context**

**Comment by gssbzn** [comment]
Hi @Freyert if you are seeing for `IncludeCount` I believe this for this has nothing to do with nested structs and more to do with the fact that field has `omitempty` and false being considered empty, https://github.com/mongodb/go-client-mongodb-atlas/blob/44ada01aee87c1ba1a6897b492117863281487d3/mongodbatlas/mongodbatlas.go#L192

To fix this we would need to change `IncludeCount` to be a pointer if you want to make that change we can review the impact as it will be a breaking change

**Comment by Freyert** [comment]
Ah! Of course! Great point.
