### ISSUE TITLE
Missing awsSecurityGroup property for ProjectIPWhitelist

### ISSUE THREAD

**Issue by gssbzn** [mongodb/go-client-mongodb-atlas#40]
the struct for `ProjectIPWhitelist` is missing a `AWSSecurityGroup` property

https://docs.atlas.mongodb.com/reference/api/whitelist-add-one/#request-body-parameters

**Comment by PacoDw** [comment]
Hello @gssbzn, the AWSSecurityGroup was added on the pr #35 

if you have another comment just let us know, thank you

**Comment by gssbzn** [comment]
@PacoDw thanks for the reply seems good to me, I'll wait then for that PR to be merged 👍
